SELECT *
  FROM PCLANC, PCCONTA, PCLOGCUSTO, PCPRODUT
 WHERE PCLANC.DTLANC >= TRUNC(SYSDATE) - 30
   AND PCLANC.CODCONTA = PCCONTA.CODCONTA
   AND PCLANC.CODCONTA IN (SELECT CODCONTAMANUTCUSTO FROM PCCONSUM)
   AND PCLOGCUSTO.CODPROD = PCPRODUT.CODPROD
   AND PCLOGCUSTO.RECNUM = PCLANC.RECNUM
   AND PCLANC.VALOR <> 0
