SELECT PCFORNEC.CODFORNEC, 
       PCFORNEC.FORNECEDOR, 
       PCFORNEC.FANTASIA, 
       PCFORNEC.CGC, 
       PCFORNEC.IE, 
       PCFORNEC.DTCADASTRO,
       PCFORNEC.DTEXCLUSAO,
       PCFORNEC.BLOQUEIO 
FROM PCFORNEC
GROUP BY CODFORNEC, FORNECEDOR, FANTASIA, CGC, IE, DTCADASTRO, DTEXCLUSAO, BLOQUEIO
HAVING COUNT (IE) > '1'