  SELECT PCEST.CODFILIAL,
         PCPRODUT.CODPROD,
         PCPRODUT.DESCRICAO,
         PCPRODUT.EMBALAGEM,
         ROUND (NVL (PCEST.CUSTOFIN, 0), 2) CUSTOFIN,
         ROUND (NVL (PCEST.CUSTOCONT, 0), 2) CUSTOCONT,
         ROUND (NVL (PCEST.CUSTOREAL, 0), 2) CUSTOREAL,
         ROUND (NVL (PCEST.VALORULTENT, 0), 2) VALORULTENT,
         ROUND (NVL (PCEST.CUSTOREP, 0), 2) CUSTOREP,
         ROUND (NVL (PCEST.CUSTOULTENT, 0), 2) CUSTOULTENT,
         NVL (PCEST.QTESTGER, 0) QTESTGER,
         ROUND (NVL (PCEST.CUSTOULTENTFIN, 0), 2) CUSTOULTENTFIN,
         NVL (PCEST.VLULTENTCONTSEMST, 0) VLULTENTCONTSEMST,
         PCEST.STBCR,
         PCEST.BASEBCR,
         NVL (PCPRODUT.PRECIFICESTRANGEIRA, 'N') PRECIFICESTRANGEIRA,
         NVL (PCEST.DTULTENT, TRUNC (SYSDATE)) DTULTENT,
         PCEST.CUSTONFSEMST,
         PCEST.CUSTOREALSEMST
    FROM PCPRODUT, PCEST
   WHERE     PCEST.CODFILIAL = '1'
         AND PCEST.CODPROD IN (SELECT CODPROD
                                 FROM PCPRODUT
                                WHERE REVENDA = 'S' AND DTEXCLUSAO IS NULL)
         AND PCEST.CODPROD = PCPRODUT.CODPROD
         AND PCEST.CUSTOFIN <> PCEST.CUSTOCONT
ORDER BY PCEST.CODPROD