SELECT PCMOV.CODFILIAL,
       PCMOV.DTMOV, 
       PCMOV.CODPROD,
       PCMOV.DESCRICAO,
       PCPRODUT.USAWMS,
       PCMOV.QTCONT,
       NVL(PCMOV.CUSTOCONT,0) CUSTOCONT,
       ROUND(NVL((PCMOV.QTCONT*PCMOV.CUSTOCONT),0),2) VLTOTAL,
       PCMOV.CODOPER,
       CASE PCMOV.CODOPER WHEN 'S' THEN 'SAIDA'
                          WHEN 'SD' THEN 'SAIDA DEVOLUCAO'
                          WHEN 'SR' THEN 'SAIDA SIMPLES REMESSA'
                          END MOVIMENTACAO,
       PCMOV.NUMNOTA,
       PCMOV.CODFISCAL CFOP,
       PCMOV.CODCLI, 
       PCCLIENT.CLIENTE,
       PCLANC.CODCONTA,
       PCCONTA.CONTA    
  FROM PCMOV, PCCLIENT,PCPRODUT, PCLANC, PCCONTA
 WHERE     CODOPER IN ('SR')
       AND PCMOV.CODPROD IN (SELECT CODPROD
                               FROM PCPRODUT
                              WHERE REVENDA = 'S' AND DTEXCLUSAO IS NULL)
       AND PCMOV.DTMOV BETWEEN '&DTINI' AND '&DTFIM'
       AND PCCLIENT.CODCLI=PCMOV.CODCLI
       AND PCPRODUT.CODPROD=PCMOV.CODPROD
       AND PCLANC.NUMTRANSVENDA=PCMOV.NUMTRANSVENDA
       AND PCCONTA.CODCONTA=PCLANC.CODCONTA