SELECT PCLOGPCPARAMFILIAL.DTALTER DATA,
       (PCLOGPCPARAMFILIAL.CODFUNC || ' - ' || PCEMPR.NOME) FUNCIONARIO,
       PCLOGPCPARAMFILIAL.NOMEPARAM PARAMETRO,
       PCMETAPARAMFILIAL.TITULO,
       DECODE(PCLOGPCPARAMFILIAL.CODFILIAL,
              '99',
              'todas',
              PCLOGPCPARAMFILIAL.CODFILIAL) FILIAL,
       PCLOGPCPARAMFILIAL.VALORANTIGO VALUEOLD,
       PCLOGPCPARAMFILIAL.VALORATUAL VALUENEW,
       PCMETAPARAMFILIAL.ID,
       PCLOGPCPARAMFILIAL.CODFILIAL
  FROM PCLOGPCPARAMFILIAL, PCMETAPARAMFILIAL, PCEMPR
 WHERE TRUNC(PCLOGPCPARAMFILIAL.DTALTER) BETWEEN '&DTINI' AND '&DTFIM'
   AND PCMETAPARAMFILIAL.ID = '&IDPARAMETRO'
   AND PCEMPR.MATRICULA = PCLOGPCPARAMFILIAL.CODFUNC
   AND PCMETAPARAMFILIAL.NOME = PCLOGPCPARAMFILIAL.NOMEPARAM
 ORDER BY PCLOGPCPARAMFILIAL.DTALTER, PCLOGPCPARAMFILIAL.NOMEPARAM