  SELECT PCPEDIDO.CODFILIAL,
         PCPEDIDO.CODFORNEC,
         PCFORNEC.FORNECEDOR,
         PCFORNEC.ESTADO UF,
         PCPEDIDO.CODCOMPRADOR,
         PCEMPR.NOME_GUERRA COMPRADOR,
         PCPEDIDO.NUMPED,
         PCPEDIDO.DTEMISSAO,
         PCPEDIDO.DTPREVCHEGADA,
         PCPEDIDO.DTCHEGADA,
         ROUND (NVL (PCPEDIDO.VLTOTAL, 0), 2) VLTOTAL,
         ROUND (NVL (PCPEDIDO.VLENTREGUE, 0), 2) VLENTREGUE,
         ROUND (NVL ( (PCPEDIDO.VLTOTAL - PCPEDIDO.VLENTREGUE), 0), 2)
            VLPENDENTE
    FROM PCPEDIDO, PCFORNEC, PCEMPR
   WHERE     PCPEDIDO.CODFORNEC = PCFORNEC.CODFORNEC
         AND PCPEDIDO.CODCOMPRADOR = PCEMPR.MATRICULA
         AND (PCPEDIDO.VLTOTAL - PCPEDIDO.VLENTREGUE) <> 0
         AND PCPEDIDO.DTEMISSAO BETWEEN TRUNC (SYSDATE) - 60
                                    AND TRUNC (SYSDATE)
ORDER BY PCPEDIDO.CODFILIAL,
         PCPEDIDO.CODFORNEC,
         (PCPEDIDO.VLTOTAL - PCPEDIDO.VLENTREGUE) DESC