SELECT PCEST.CODFILIAL,
       PCPRODUT.CODPROD,
       PCPRODUT.DESCRICAO,
       PCPRODUT.EMBALAGEM,
       PCPRODUT.UNIDADE,
       CASE WHEN PCPRODUT.OBS2 = 'S' THEN 'FORA LINHA' ELSE 'ATIVO' END
          "FORALINHA",
       PCEST.QTESTGER,
       PCEST.QTBLOQUEADA,
       PCEST.QTINDENIZ,
       PCEST.QTRESERV,
       (PCEST.QTESTGER - PCEST.QTBLOQUEADA - PCEST.QTINDENIZ - PCEST.QTRESERV)
          QTDISPONIVEL,
       PCEST.DTULTENT
  FROM PCPRODUT, PCEST
 WHERE PCPRODUT.CODPROD = PCEST.CODPROD AND PCEST.QTESTGER < 0
 ORDER BY PCPRODUT.DESCRICAO, PCEST.QTESTGER DESC