
SELECT nvl(round(sum(comple.vlicms * p.qtcont), 2),0) valor
  FROM PCMOV        P,
       PCPRODFILIAL PF,
       PCNFENT      NF,
       PCPRODUT     PROD,
       pcmovcomple  comple
 WHERE P.CODPROD = PF.CODPROD
   AND NF.NUMTRANSENT = P.NUMTRANSENT
   AND NF.CODFILIAL = PF.CODFILIAL
   AND comple.numtransitem = P.numtransitem
   AND PF.CODPROD = P.CODPROD
   AND P.CODPROD = PROD.CODPROD
   AND NF.ESPECIE = 'NF'
   AND P.GERAICMSLIVROFISCAL = 'N'
   AND P.CODOPER IN ('E', 'ED', 'ER', 'EB', 'E')
   AND P.CODFISCAL NOT IN (1403, 2403, 1551, 2551, 1556, 2556)
   AND P.SITTRIBUT NOT IN ('10', '60', '70', '40')
   AND P.PUNITCONT > 0
   AND P.PERCICM > 0
   AND NF.ESPECIE = 'NF'
   AND (NVL(P.ST, 0) = 0 AND NVL(P.PERCDESPADICIONAL, 0) = 0)
   AND NVL(P.PERICMSANTECIPADO, 0) = 0
   AND NF.DTENT BETWEEN
       TO_DATE('01/' || TO_CHAR(ADD_MONTHS(TRUNC(SYSDATE), -1), 'MM/YYYY'),
               'DD/MM/YYYY') AND ADD_MONTHS(TRUNC(SYSDATE), -1)
