SELECT PCPRODUT.CODPROD, 
       PCPRODUT.DESCRICAO,
       PCPRODUT.CODAUXILIAR, 
       PCPRODUT.CODAUXILIARTRIB,
       PCPRODUT.CODAUXILIAR2,
       PCPRODUT.CODFORNEC,
       PCPRODUT.STATUS,
       PCPRODUT.DTCADASTRO,
       PCPRODUT.CODFUNCCADASTRO,
       PCEMPR.NOME_GUERRA
FROM PCPRODUT, PCEMPR
WHERE PCPRODUT.CODFUNCCADASTRO=PCEMPR.MATRICULA
AND PCPRODUT.CODAUXILIAR IS NULL
AND PCPRODUT.CODAUXILIAR2 IS NULL
AND PCPRODUT.CODAUXILIARTRIB IS NULL
ORDER BY PCPRODUT.CODPROD