SELECT PCVERBA.NUMVERBA,
       PCVERBA.CODFILIAL,
       PCFORNEC.CODFORNECPRINC CODFORNEC,
       PCFORNEC.CODFORNEC CODFOR,
       PCFORNEC.FORNECEDOR,
       PCVERBA.DTEMISSAO,
       PCVERBA.DTVENC,
       PCVERBA.TIPO,
       PCVERBA.DTVENC,
       DECODE(PCVERBA.FORMAPGTO, 'M', 'MERCADORIA', 'DINHEIRO') FORMAPGTO,
       NVL(PCVERBA.VALOR, 0) VALOR,
       (SELECT SUM(VLAPLIC)
          FROM PCAPLICVERBA
         WHERE PCAPLICVERBA.NUMVERBA = PCVERBA.NUMVERBA) VLAPLIC,
                (NVL(PCVERBA.VALOR, 0) -
       NVL((SELECT SUM(NVL(PCAPLICVERBA.VLAPLIC, 0))
              FROM PCAPLICVERBA
             WHERE PCAPLICVERBA.NUMVERBA = PCVERBA.NUMVERBA),
            0)) SALDOAPLICAR,
       PCVERBA.CODCONTA,
       PCVERBA.REFERENCIA,
       PCCONTA.CONTA,
       PCNFSAID.NUMNOTA AS NUMNOTADEV
  FROM PCVERBA, PCCONTA, PCFORNEC, PCEMPR, PCCONSUM, PCNFSAID
 WHERE PCVERBA.CODCONTA = PCCONTA.CODCONTA
   AND PCVERBA.CODFORNEC = PCFORNEC.CODFORNEC
   AND PCVERBA.CODFUNCCANCEL = PCEMPR.MATRICULA(+)
   AND PCVERBA.NUMTRANSENTDEVFORNEC = PCNFSAID.NUMTRANSVENDA(+)
   AND PCVERBA.CODFILIAL = &CODFILIAL
   AND DTVENC BETWEEN '&DTINI' AND '&DTFIM'
   AND PCFORNEC.CODFORNEC BETWEEN 1 AND 999999
   AND EXISTS (SELECT NUMVERBA
          FROM PCMOVCRFOR
         WHERE PCMOVCRFOR.NUMVERBA = PCVERBA.NUMVERBA
           AND DTCONCIL IS NULL)
   AND PCVERBA.FORMAPGTO IN ('D', 'M', 'R')
 ORDER BY PCFORNEC.CODFORNECPRINC, PCVERBA.NUMVERBA
